name: CI

on:
  push:
    branches:
      - saucelabs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  saucelabs:
    runs-on: ubuntu-latest
    env:
      KARMA_PARALLEL_BROWSERS: 2
      CI_NODE_INDEX: 0
      CI_NODE_TOTAL: 1
      CI_RUNNER_NUMBER: ${{ github.run_id }}
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@01c8c16f830d02110c28640aea16f145a7937080
        with:
          cache-node-modules: true
      - name: Install node modules
        run: yarn install --frozen-lockfile
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@01c8c16f830d02110c28640aea16f145a7937080
      - name: Setup Saucelabs Variables
        uses: angular/dev-infra/github-actions/saucelabs@01c8c16f830d02110c28640aea16f145a7937080
      - name: Run tests on Saucelabs
        run: ./scripts/circleci/run-saucelabs-tests.sh
